language: node_js
sudo: false
node_js:
  - "0.12"
  - "1.0"
  - "1.1"
  - "1.3"
  - "1.5"
  - "1.7"
  - "2.0"
  - "2.1"
  - "2.3"
  - "2.5"
  - "3.0"
  - "3.1"
  - "3.3"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
  - "5.1"
  - "5.3"
  - "5.5"
  - "5.7"
  - "5.11"
  - "6.0"
notifications:
  email:
    on_success: never
services:
  - mongodb
script: "npm run-script test-cov"
after_script: "cat ./coverage/lcov.info | coveralls"
env:
  - CC=clang CXX=clang++ npm_config_clang=1
before_install:
  - if [ "$(npm -v | cut -c1)" == '1' ]; then npm -g i npm@2; fi
